### PR TITLE
Converting the VS build instructions wiki page to a step-by step guide

### PR DESCRIPTION
**Pull request by mrtnptrs**
-Adding a list of programs which have to installed
-Shorten some parts a bit
-Left some notes about the S1023 DirectX SDK error.

### CODE REVIEW

**Comment by mrtnptrs** [comment]
I now converted this to a step-by-step guide. This makes it easier to follow the guide.

**Comment by OmniBlade** [comment]
Okay, few notes.

For requirements I would say "I order to build Thyme" rather than "To make building Thyme possible".
Also, the correct SDK for DIrect3D8 is I believe the Aug 2007 SDK https://www.microsoft.com/en-gb/download/details.aspx?id=13287 though the repo actually includes the needed header for that.

For the additional notes, I would drop the sentence about it being the most straight forward compiler, this is already the guide specifically for MSVC, it doesn't need to sell it, that is the generic guides job to steer people to the correct one to use.

Under "Building Thyme", "Downloading the source using Cmake" should be "Downloading the source using git"

**Comment by mrtnptrs** [comment]
Ok, I will apply those changes tomorrow.

But as I tested it with the 2010 SDK and it worked (build also ran perfectly), why wouldn't we use that one? :)

**Comment by OmniBlade** [comment]
It works because the Thyme repo hosts the missing headers and import lib and has a tweaked cmake module for finding it, but it is theoretically possible I be asked to remove those at some point so we might as well tell people which the correct SDK is for it to work without relying on the repo continuing to host the additional files IMO.

**Comment by mrtnptrs** [comment]
Sorry for making the changes so late. Have been busy and actually kinda forgot it, oops.... It should now be ready to merge.

**Pull request merged**
